network_monitor/network_monitor/core/urls.py
from django.conf.urls import url, include
from django.conf import settings

from network_monitor.helpers.utils import NotFoundView
from .views import IndexView, RegisterView, LoginView, LogoutView, \
    ProfileView, ChangePasswordView, DeviceListView, DeviceAddView, \
    DeviceEditView, DeviceDeleteView, DeviceFeaturesView, EventListView, \
    EventDeleteView, UserAlertRuleListView, UserAlertRuleAddView, \
    UserAlertRuleEditView, UserAlertRuleDeleteView, DeviceSwitchActiveView, UserAlertRuleSwitchActiveView, \
    DevicesStatusAjaxView, DevicePrintLabelView, DiscoverDeviceView, StopDiscoverDeviceView, DeviceFixMacView, \
    PingTestDeviceView, SettingGeneralView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^register/$', (RegisterView if settings.ENABLE_REGISTER_USER_VIEW else NotFoundView).as_view(),
        name="register"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/$', ProfileView.as_view(), name="profile"),
    url(r'^change-password/$', ChangePasswordView.as_view(), name="change-password"),
    url(r'^event/list/$', EventListView.as_view(), name="event-list"),
    url(r'^event/delete/(?P<pk>\d+)/$', EventDeleteView.as_view(), name="event-delete"),
    url(r'^device/list/$', DeviceListView.as_view(), name="device-list"),
    url(r'^device/add/$', DeviceAddView.as_view(), name="device-add"),
    url(r'^device/discover/$', DiscoverDeviceView.as_view(), name="device-discover"),
    url(r'^device/discover/stop/$', StopDiscoverDeviceView.as_view(), name="device-discover-stop"),
    url(r'^device/edit/(?P<pk>\d+)/$', DeviceEditView.as_view(), name="device-edit"),
    url(r'^device/fixmac/(?P<pk>\d+)/$', DeviceFixMacView.as_view(), name="device-fixmac"),
    url(r'^device/switch-active/(?P<pk>\d+)/$', DeviceSwitchActiveView.as_view(), name="device-switch-active"),
    url(r'^device/delete/(?P<pk>\d+)/$', DeviceDeleteView.as_view(), name="device-delete"),
    url(r'^device/print-label/(?P<pk>\d+)/$', DevicePrintLabelView.as_view(), name="device-print-label"),
    url(r'^device/features/(?P<pk>\d+)/$', DeviceFeaturesView.as_view(), name="device-features"),
    url(r'^device/status/(?P<pk>((\d+),?)+)/$', DevicesStatusAjaxView.as_view(), name="device-status"),
    url(r'^device/ping-test/(?P<pk>\d+)/$', PingTestDeviceView.as_view(), name="device-ping-test"),
    url(r'^user_alert_rule/list/$', UserAlertRuleListView.as_view(), name="user_alert_rule-list"),
    url(r'^user_alert_rule/add/$', UserAlertRuleAddView.as_view(), name="user_alert_rule-add"),
    url(r'^user_alert_rule/edit/(?P<pk>\d+)/$', UserAlertRuleEditView.as_view(), name="user_alert_rule-edit"),
    url(r'^user_alert_rule/switch-active/(?P<pk>\d+)/$', UserAlertRuleSwitchActiveView.as_view(), name="user_alert_rule-switch-active"),
    url(r'^user_alert_rule/delete/(?P<pk>\d+)/$', UserAlertRuleDeleteView.as_view(), name="user_alert_rule-delete"),
    url(r'^settings/general', SettingGeneralView.as_view(), name="settings-general"),
]

network_monitor/network_monitor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from network_monitor.core.views import DeviceFeatureConfigView, DeviceFeatureChartsView, \
    DeviceFeatureThresholdListView, DeviceFeatureThresholdDeleteView, \
    DeviceFeatureThresholdSwitchView, DeviceFeatureThresholdAddView


urlpatterns = [
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('network_monitor.core.urls', namespace='core')),
]
for app in settings.INSTALLED_FEATURES:
    f = app.split('.')[-3]
    app_urls = '.'.join(app.split('.')[:-2]+['urls'])
    urlpatterns.append(url(r'^device/(?P<device_id>\d+)/{}/'.format(f), include(app_urls), kwargs={'feature': f}))

# default device_features routing
urlpatterns.extend([
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/config/$',
        DeviceFeatureConfigView.as_view(), name="device-feature-config"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/charts/$',
        DeviceFeatureChartsView.as_view(), name="device-feature-charts"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/list/$',
        DeviceFeatureThresholdListView.as_view(),
        name="device-feature-threshold-list"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/add/(?P<threshold_type>.+)/$',
        DeviceFeatureThresholdAddView.as_view(),
        name="device-feature-threshold-add"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/delete/(?P<threshold_id>\d+)/$',
        DeviceFeatureThresholdDeleteView.as_view(),
        name="device-feature-threshold-delete"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/switch/(?P<threshold_id>\d+)/$',
        DeviceFeatureThresholdSwitchView.as_view(),
        name="device-feature-threshold-switch"),
])

network_monitor/network_monitor/core/models.py
import string
import jsonfield
import operator
from functools import reduce
from django.db.models import Q
from django.utils import timezone
from django.apps import apps
from django.db import models
from django.dispatch import receiver
from django.db import IntegrityError
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.validators import MinValueValidator
from phonenumber_field.modelfields import PhoneNumberField

from network_monitor.helpers.shortcuts import get_installed_features
from network_monitor.helpers.utils import SafeFormat, MACAddressField, find_mac_manufacture

SEVERITY_CLEAR = 0
SEVERITY_DEBUG = 1
SEVERITY_INFO = 2
SEVERITY_WARNING = 3
SEVERITY_ERROR = 4
SEVERITY_CRITICAL = 5

SEVERITY_CHOICES = (
    (SEVERITY_CRITICAL, 'Critical'),
    (SEVERITY_ERROR, 'Error'),
    (SEVERITY_WARNING, 'Warning'),
    (SEVERITY_INFO, 'Info'),
    (SEVERITY_DEBUG, 'Debug'),
    (SEVERITY_CLEAR, 'Clear'),
)


class Device(models.Model):
    STATUS_UP = 'up'
    STATUS_DOWN = 'down'
    STATUS_CHOICES = (
        (STATUS_UP, 'Up'),
        (STATUS_DOWN, 'Down'),
    )

    name = models.CharField("Name", max_length=256, unique=True)
    address = models.GenericIPAddressField("IP Address")
    web_port = models.PositiveSmallIntegerField("Web Port", null=True, blank=True)
    mac = MACAddressField('Mac Address', null=True, blank=True, unique=True)
    mac_manufacture = models.CharField(max_length=128, null=True, blank=True)
    username = models.CharField("Username", max_length=128, null=True,
                                blank=True)
    password = models.CharField("Password", max_length=128, null=True,
                                blank=True)
    location = models.CharField("Location", max_length=512,
                                null=True, blank=True)
    purchase_date = models.DateField(null=True, blank=True)
    manufacture_date = models.DateField(null=True, blank=True)
    warranty_expiration_date = models.DateField(null=True, blank=True)
    note = models.TextField("Note", null=True, blank=True)
    status = models.CharField('Status', max_length=16, choices=STATUS_CHOICES, default=STATUS_DOWN)
    tags = models.CharField('Tags', max_length=1024, blank=True, null=True, default=None)
    last_seen = models.DateTimeField("Last Seen", null=True)
    created = models.DateTimeField("Created At", auto_now_add=True)
    active = models.BooleanField("Active", default=True)

    @classmethod
    def secret_fields(self):
        return ['password']

    @property
    def active_features(self):
        return [f.feature for f in self.feature.filter(active=True).order_by('feature')]

    @property
    def status_display(self):
        return dict(self.STATUS_CHOICES).get(self.status, self.STATUS_DOWN)

    @property
    def web_url(self):
        return 'http://{}{}'.format(self.address, ':{}'.format(self.web_port) if self.web_port else '')

    def fetch_mac_manufacture(self, abort=False):
        if not self.mac:
            return
        return find_mac_manufacture(self.mac, abort=abort)

    class Meta:
        permissions = (
            ('access_device_secret_data', 'Can access device secret data'),
            ('ping_test_device', 'Can send ping test for device'),
        )

    def save(self, *args, **kwargs):
        if self.mac == '':
            self.mac = None
        return super(Device, self).save(*args, **kwargs)

    def __str__(self):
        return self.name.capitalize()


class DeviceFeature(models.Model):
    FEATURE_CHOICES = tuple([(a, a) for a in get_installed_features()])
    device = models.ForeignKey(Device, on_delete=models.CASCADE,
                               related_name='feature')
    feature = models.CharField('Feature Name', max_length=128,
                               choices=FEATURE_CHOICES)
    round_interval = models.PositiveIntegerField(
        "Round Interval(Seconds)", blank=False, null=False, default=60,
        validators=[MinValueValidator(1)])
    last_round = models.DateTimeField('Last Round', blank=True,
                                      null=True)
    active = models.BooleanField("Enabled?", default=False)
    args = jsonfield.JSONField('Feature Args', null=False, blank=True,
                               default=dict)
    conf = jsonfield.JSONField('Feature Conf', null=False, blank=True,
                               default=dict)

    class Meta:
        unique_together = (("device", "feature"),)

    @property
    def app_feature(self):
        return apps.get_app_config(self.feature)

    def __str__(self):
        return '{}(device={})'.format(self.feature, self.device)


class Threshold(models.Model):

    device_feature = models.ForeignKey(DeviceFeature, on_delete=models.CASCADE,
                                       related_name='threshold')
    name = models.CharField('Name', max_length=128)
    type = models.CharField('Type', max_length=128)
    severity = models.SmallIntegerField('Severity', choices=SEVERITY_CHOICES,
                                        default=SEVERITY_INFO)
    trigger_time = models.DateTimeField("Trigger Time", null=True)
    clear_time = models.DateTimeField("Clear Time", null=True)
    active = models.BooleanField("Active?", default=True)
    data = jsonfield.JSONField('Data', null=False, blank=False,
                               default=dict)

    @property
    def severity_display(self):
        return dict(SEVERITY_CHOICES).get(self.severity)

    def trigger(self):
        self.trigger_time = timezone.now()
        self.clear_time = None

    def clear(self):
        self.clear_time = timezone.now()

    @property
    def threshold_object(self):
        from network_monitor.monit_manager.threshold import Manager
        th_cls = Manager.get_threshold_cls(self.type)
        args = self.data.get('args', ())
        kwargs = self.data.get('kwargs', {})
        return th_cls(*args, **kwargs)

    def __str__(self):
        return self.name


class Event(models.Model):

    device = models.ForeignKey(Device, on_delete=models.CASCADE,
                               related_name='event', null=True)
    threshold = models.ForeignKey(Threshold, on_delete=models.SET_NULL,
                                  related_name='event', null=True)
    feature = models.CharField('Feature Name', max_length=128, null=True)
    severity = models.SmallIntegerField('Severity', choices=SEVERITY_CHOICES,
                                        default=SEVERITY_INFO)
    summary = models.CharField('Summary', max_length=512, null=True)
    message = models.TextField('Message', max_length=10240)
    first_time = models.DateTimeField('First Time', auto_now_add=True)
    last_time = models.DateTimeField('Last Time', default=timezone.now)
    count = models.PositiveIntegerField("Count", default=1)
    clear_time = models.DateTimeField("Clear Time", null=True)
    notify_time = models.DateTimeField("Notify Time", null=True)
    seen = models.BooleanField("Seen?", default=False)

    @property
    def severity_display(self):
        return dict(SEVERITY_CHOICES).get(self.severity)

    def clear(self):
        self.clear_time = timezone.now()

    @classmethod
    def create_or_update(cls, **kwargs):
        if kwargs.get('threshold'):
            args = dict(
                clear_time=None,
                severity=kwargs.pop('severity', SEVERITY_INFO),
                threshold=kwargs.pop('threshold', None),
                device=kwargs.pop('device', None),
                feature=kwargs.pop('feature', None),
            )
            kwargs.pop('clear_time', None)
            obj = cls.objects.filter(**args).first()
            if not obj:
                args.update(kwargs)
                obj = cls.objects.create(**args)
            else:
                obj.last_time = timezone.now()
                obj.count += 1
                obj.save()
        else:
            obj = cls.objects.create(**kwargs)

        return obj

    def save(self, *args, **kwargs):
        if self.severity == SEVERITY_CLEAR and self.clear_time is None:
            self.clear()
        return super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return '{} Event({})'.format(self.severity_display, self.summary)


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name="profile",
                                on_delete=models.CASCADE)
    sms_number = PhoneNumberField(blank=True, null=True)

    def __str__(self):
        return '{}'.format(self.user)


class RuleComilerException(Exception):
    pass


class RulesCompiler(object):
    OPERATORS = dict(
        eq=lambda f, v: Q(**{f: v}),
        neq=lambda f, v: ~Q(**{f: v}),
        gt=lambda f, v: Q(**{f+'__gt': v}),
        gte=lambda f, v: Q(**{f+'__gte': v}),
        lt=lambda f, v: Q(**{f+'__lt': v}),
        lte=lambda f, v: Q(**{f+'__lte': v}),
        contains=lambda f, v: Q(**{f+'__contains': v}),
        icontains=lambda f, v: Q(**{f+'__icontains': v}),
        startswith=lambda f, v: Q(**{f+'__startswith': v}),
        endswith=lambda f, v: Q(**{f+'__endswith': v}),
    )

    def __init__(self, rules):
        self.rules = rules
        assert rules, 'rules cannot be empty'

    def compile(self):
        q_list = []
        rule_conditions = self.rules.get('conditions')
        join_by = operator.or_ if self.rules.get('join_by') == 'or'\
            else operator.and_
        for rule in rule_conditions:
            try:
                op = rule['o']
                parameter = rule['p']
                value = rule['v']
            except KeyError:
                raise RuleComilerException('Invalid rule')
            if op not in self.OPERATORS:
                raise RuleComilerException('Invalid operator')
            q = self.OPERATORS[op](parameter, value)
            q_list.append(q)

        return reduce(join_by, q_list)


MEDIA_SMS = 'sms'
MEDIA_EMAIL = 'email'
MEDIA_WEB = 'web'

network_monitor/network_monitor/core/templates/network_monitor/core/event/list.html
{% extends "network_monitor/core/base.html" %}
{% load humanize %}
{% load pagination_tags %}
{% load util_tags %}

{% block extra_css %}
    <link href="{{ STATIC_URL }}css/chosen.min.css" rel="stylesheet">
{% endblock %}

{% block breadcrumb_items %}
    <li>Event List</li>
{% endblock %}

{% block content %}
    <h3 class="page-title">Event List</h3>
    <div id="filters" class="filters">
        <h5 class="subtitle">Filters</h5>
        <form id="filterForm" class="form-inline" role="form" action="">
            {% if request.GET.order_by %}
            <input type="hidden" name="order_by" value="{{ request.GET.order_by }}">
            {% endif %}
            <input type="hidden" name="page_size" value="{{ request.GET.page_size }}">
            {% for field in events.form.visible_fields %}
            {% if field.name != 'order_by' %}
            <div class="form-group">
              {{ field }}
            </div>
            {% endif %}
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-sm" title="Apply Filter"><span class="fa fa-filter"></span></button>
            <button type="reset" class="btn btn-danger btn-sm clear-filter" title="Clear All Filters"><span class="fa fa-close"></span></button>
        </form>
    </div>


    <table class="table table-hover table-advance">
        <tr>
            <th>{% sorting_link 'ID#' 'id' %}</th>
            <th>{% sorting_link 'Severity' 'severity' %}</th>
            <th>{% sorting_link 'Feature' 'feature' %}</th>
            <th>{% sorting_link 'Device' 'device' %}</th>
            <th>{% sorting_link 'Threshold' 'threshold' %}</th>
            <th>{% sorting_link 'Summary' 'summary' %}</th>
            <th>{% sorting_link 'Message' 'message' %}</th>
            <th>{% sorting_link 'First Time' 'first_time' %}</th>
            <th>{% sorting_link 'Last Time' 'last_time' %}</th>
            <th>{% sorting_link 'Count' 'count' %}</th>
            <th>{% sorting_link 'Clear Time' 'clear_time' %}</th>
            <th class="event-list-table-actions-col">Actions</th>
        </tr>
        {% with events.qs as qs %}
        {% autopaginate qs page_size %}
        {% for event in qs %}
        <tr data-id="{{event.id}}">
            <td>{{ event.id }}</td>
            <td>{{ event.severity|severity_tag }}</td>
            <td>{{ event.feature }}</td>
            <td><a href="{% url 'core:device-features' event.device.pk %}">{{ event.device }}</a></td>
            <td>{{ event.threshold|default:'-' }}</td>
            <td><span data-toggle="tooltip" data-placement="bottom" data-html="true" title="{{ event.summary|default:'NO MESSAGE!'|safe }}">{{ event.summary|striptags|truncatechars:50|default:'-' }}</span></td>
            <td><span data-toggle="tooltip" data-placement="bottom" data-html="true" title="{{ event.message|default:'NO MESSAGE!'|safe }}">{{ event.message|striptags|truncatechars:50|default:'-' }}</span></td>
            <td title="{{event.first_time}}">{{ event.first_time|naturaltime }}</td>
            <td title="{{event.last_time}}">{{ event.last_time|naturaltime }}</td>
            <td>{{ event.count }}</td>
            <td title="{{event.clear_time|default:'Not cleared yet!'}}">{{ event.clear_time|naturaltime|default:'-' }}</td>
            <td>
                <button class="btn btn-sm btn-danger" name="delete-event"><span class="fa fa-trash"></span></button>
            </td>

        </tr>
        {% empty %}
        <tr><td class="text-center gray-color" colspan="11"> <em>[NO RECORD!]</em></td></tr>
        {% endfor %}
    </table>
    {% paginate %}
    <div class="pull-right mar-top20">
        {% pagination_info %}
        {% page_size_combo %}
    </div>
    {% endwith %}

{% include "network_monitor/core/partials/action_modal.html" with prefix_id='action' message_class='text-danger' %}

{% endblock %}

{% block extra_js %}
<script src="{{ STATIC_URL }}js/chosen.jquery.min.js"></script>
<script src="{{ STATIC_URL }}js/utils.js"></script>

<script type="text/javascript">
$(document).ready(function () {
    $('#filterForm [name][type!=hidden]').on('change', function(e) {
        var form = $(this).parents('form');
        form.submit();
    });
    $('.page-size').on('change', function() {
        $('input[name=page_size]').val($(this).val());
        $('#filterForm').submit();
    });

    $('.chosen-select-deselect').chosen({allow_single_deselect:true});
    $('#id_severity').chosen({allow_single_deselect:true});
    $('#id_threshold').chosen({allow_single_deselect:true});
    $('#id_device').chosen({allow_single_deselect:true});

    $('.clear-filter').click(function() {
        var form = $(this).parents('form');
        $('[name][type!=hidden]', form).val('').attr('disabled', true).trigger("chosen:updated");
        form.submit();
    });
    bindModalAction('actionModal', 'button[name=delete-event]', 'Delete Event', 'Are you sure to delete?', '{% url 'core:event-delete' 0 %}');
});
</script>
{% endblock %}