network_monitor/network_monitor/core/urls.py
from django.conf.urls import url, include
from django.conf import settings

from network_monitor.helpers.utils import NotFoundView
from .views import IndexView, RegisterView, LoginView, LogoutView, \
    ProfileView, ChangePasswordView, DeviceListView, DeviceAddView, \
    DeviceEditView, DeviceDeleteView, DeviceFeaturesView, EventListView, \
    EventDeleteView, UserAlertRuleListView, UserAlertRuleAddView, \
    UserAlertRuleEditView, UserAlertRuleDeleteView, DeviceSwitchActiveView, UserAlertRuleSwitchActiveView, \
    DevicesStatusAjaxView, DevicePrintLabelView, DiscoverDeviceView, StopDiscoverDeviceView, DeviceFixMacView, \
    PingTestDeviceView, SettingGeneralView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^register/$', (RegisterView if settings.ENABLE_REGISTER_USER_VIEW else NotFoundView).as_view(),
        name="register"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/$', ProfileView.as_view(), name="profile"),
    url(r'^change-password/$', ChangePasswordView.as_view(), name="change-password"),
    url(r'^event/list/$', EventListView.as_view(), name="event-list"),
    url(r'^event/delete/(?P<pk>\d+)/$', EventDeleteView.as_view(), name="event-delete"),
    url(r'^device/list/$', DeviceListView.as_view(), name="device-list"),
    url(r'^device/add/$', DeviceAddView.as_view(), name="device-add"),
    url(r'^device/discover/$', DiscoverDeviceView.as_view(), name="device-discover"),
    url(r'^device/discover/stop/$', StopDiscoverDeviceView.as_view(), name="device-discover-stop"),
    url(r'^device/edit/(?P<pk>\d+)/$', DeviceEditView.as_view(), name="device-edit"),
    url(r'^device/fixmac/(?P<pk>\d+)/$', DeviceFixMacView.as_view(), name="device-fixmac"),
    url(r'^device/switch-active/(?P<pk>\d+)/$', DeviceSwitchActiveView.as_view(), name="device-switch-active"),
    url(r'^device/delete/(?P<pk>\d+)/$', DeviceDeleteView.as_view(), name="device-delete"),
    url(r'^device/print-label/(?P<pk>\d+)/$', DevicePrintLabelView.as_view(), name="device-print-label"),
    url(r'^device/features/(?P<pk>\d+)/$', DeviceFeaturesView.as_view(), name="device-features"),
    url(r'^device/status/(?P<pk>((\d+),?)+)/$', DevicesStatusAjaxView.as_view(), name="device-status"),
    url(r'^device/ping-test/(?P<pk>\d+)/$', PingTestDeviceView.as_view(), name="device-ping-test"),
    url(r'^user_alert_rule/list/$', UserAlertRuleListView.as_view(), name="user_alert_rule-list"),
    url(r'^user_alert_rule/add/$', UserAlertRuleAddView.as_view(), name="user_alert_rule-add"),
    url(r'^user_alert_rule/edit/(?P<pk>\d+)/$', UserAlertRuleEditView.as_view(), name="user_alert_rule-edit"),
    url(r'^user_alert_rule/switch-active/(?P<pk>\d+)/$', UserAlertRuleSwitchActiveView.as_view(), name="user_alert_rule-switch-active"),
    url(r'^user_alert_rule/delete/(?P<pk>\d+)/$', UserAlertRuleDeleteView.as_view(), name="user_alert_rule-delete"),
    url(r'^settings/general', SettingGeneralView.as_view(), name="settings-general"),
]

network_monitor/network_monitor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from network_monitor.core.views import DeviceFeatureConfigView, DeviceFeatureChartsView, \
    DeviceFeatureThresholdListView, DeviceFeatureThresholdDeleteView, \
    DeviceFeatureThresholdSwitchView, DeviceFeatureThresholdAddView


urlpatterns = [
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('network_monitor.core.urls', namespace='core')),
]
for app in settings.INSTALLED_FEATURES:
    f = app.split('.')[-3]
    app_urls = '.'.join(app.split('.')[:-2]+['urls'])
    urlpatterns.append(url(r'^device/(?P<device_id>\d+)/{}/'.format(f), include(app_urls), kwargs={'feature': f}))

# default device_features routing
urlpatterns.extend([
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/config/$',
        DeviceFeatureConfigView.as_view(), name="device-feature-config"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/charts/$',
        DeviceFeatureChartsView.as_view(), name="device-feature-charts"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/list/$',
        DeviceFeatureThresholdListView.as_view(),
        name="device-feature-threshold-list"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/add/(?P<threshold_type>.+)/$',
        DeviceFeatureThresholdAddView.as_view(),
        name="device-feature-threshold-add"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/delete/(?P<threshold_id>\d+)/$',
        DeviceFeatureThresholdDeleteView.as_view(),
        name="device-feature-threshold-delete"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/switch/(?P<threshold_id>\d+)/$',
        DeviceFeatureThresholdSwitchView.as_view(),
        name="device-feature-threshold-switch"),
])

network_monitor/network_monitor/core/views.py
import json
import subprocess

from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import Http404
from django.views.generic.base import TemplateView
from django.views.generic import View
from django.views.generic.edit import UpdateView
from django.conf import settings
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.views import password_change
from django.views.generic.edit import CreateView
from django.views.generic.detail import SingleObjectMixin
from dynamic_preferences.forms import global_preference_form_builder
from dynamic_preferences.registries import global_preferences_registry

from network_monitor.celery import app
from network_monitor.helpers.shortcuts import get_redis_mem
from network_monitor.core.tasks import nmap_scan_network
from network_monitor.helpers.utils import send_form_errors, success_message, \
    PermissionRequiredMixin, get_current_page_size, find_mac_manufacture, to_dict, warning_message
from .forms import RegistrationForm, LoginForm, ProfileForm, DeviceForm, \
    DeviceFeatureForm, ThresholdForm, UserAlertRuleForm, DiscoverDeviceForm, DeviceFixMacForm
from .filters import DevicesFilter, EventsFilter
from .models import Device, DeviceFeature, Threshold, Event, UserAlertRule, \
    SEVERITY_CHOICES
try:
    from network_monitor.helpers.utils import py2_subprocess_run as subprocess_run
except ImportError:
    from subprocess import run as subprocess_run


class IndexView(PermissionRequiredMixin, View):
    permission_required = ()

    def get(self, request, *args, **kwargs):
        ctx = {}
        return render(request, "network_monitor/core/index.html", ctx)


class RegisterView(View):

    def get(self, request, *args, **kwargs):
        form = RegistrationForm()
        ctx = {"form": form}
        return render(request, "network_monitor/core/register.html", ctx)

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST)
        password = request.POST.get('password')
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(password)
            user.save()
            success_message('User registered successfully', request)
            return redirect(self.get_success_url())
        else:
            send_form_errors(form, request)
        ctx = {"form": form}
        return render(request, "network_monitor/core/register.html", ctx)

    def get_success_url(self):
        return settings.LOGIN_URL


class LoginView(View):
    template_name = "network_monitor/core/login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(settings.LOGIN_REDIRECT_URL)
        form = LoginForm()
        ctx = {"form": form}
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            next = request.GET.get('next') or settings.LOGIN_REDIRECT_URL
            return redirect(next)
        else:
            send_form_errors(form, request)
        ctx = {"form": form}
        return render(request, self.template_name, ctx)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return redirect(settings.LOGIN_URL)


class ProfileView(PermissionRequiredMixin, UpdateView):
    permission_required = ()
    form_class = ProfileForm
    template_name = 'network_monitor/core/profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        result = super(ProfileView, self).form_valid(form)
        success_message('Profile updated successfully.', self.request)
        return result

    def get_initial(self):
        profile = self.object.profile
        return {
            field: getattr(profile, field, None)
            for field in self.form_class.Meta._profile_fields
        }

    def get_success_url(self):
        return reverse('core:profile')


class ChangePasswordView(PermissionRequiredMixin, View):
    permission_required = ()

    def get(self, request, *args, **kwargs):
        self.get_success_url()
        return password_change(
            request, template_name='network_monitor/core/change_password.html',
            post_change_redirect=self.get_success_url(),)

    def post(self, request, *args, **kwargs):
        redirect_url = self.get_success_url()
        response = password_change(
            request, template_name='network_monitor/core/change_password.html',
            post_change_redirect=redirect_url)
        if response.status_code == 302 and response.url == redirect_url:
            success_message('Password changed successfully.', request)
        return response

    def get_success_url(self):
        return reverse('core:profile')


class DeviceListView(PermissionRequiredMixin, View):
    permission_required = 'core.view_device'

    def get(self, request, *args, **kwargs):
        qs = Device.objects.order_by('-active', 'id', )
        devices = DevicesFilter(self.request.GET, queryset=qs)
        ctx = {'devices': devices, 'page_size': get_current_page_size(request)}
        return render(request, "network_monitor/core/device/list.html", ctx)


class DeviceAddView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_device'
    form_class = DeviceForm
    template_name = 'network_monitor/core/device/add.html'

    def get_form(self, form_class=None):
        form = super(DeviceAddView, self).get_form(form_class=form_class)
        if not self.request.user.has_perm("core.access_device_secret_data"):
            for sf in Device.secret_fields():
                form.fields.pop(sf, None)
        return form

    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse({'message': 'Invalid parameters', 'errors': form.errors}, status=400)
        return super(DeviceAddView, self).form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.mac:
            self.object.mac_manufacture = self.object.fetch_mac_manufacture()
        self.object.save()
        if self.request.is_ajax():
            return JsonResponse(to_dict(self.object, fields=['id', 'name', 'address', 'mac']))

        success_message('Device "{}" created successfully.'.format(self.object), self.request)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('core:device-list')


class DeviceEditView(PermissionRequiredMixin, UpdateView):
    permission_required = {
        'get': 'core.view_device',
        'post': 'core.change_device'
    }
    pk_url_kwarg = 'pk'
    form_class = DeviceForm
    model = Device
    template_name = 'network_monitor/core/device/edit.html'

    def get_form(self, form_class=None):
        form = super(DeviceEditView, self).get_form(form_class=form_class)
        if not self.request.user.has_perm("core.access_device_secret_data"):
            for sf in Device.secret_fields():
                form.fields.pop(sf, None)
        return form

    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse({'message': 'Invalid parameters', 'errors': form.errors}, status=400)
        return super(DeviceEditView, self).form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if 'mac' in form.changed_data or not self.object.mac_manufacture:
            self.object.mac_manufacture = self.object.fetch_mac_manufacture()
        self.object.save()
        if self.request.is_ajax():
            return JsonResponse(to_dict(self.object, fields=['id', 'name', 'address', 'mac']))

        success_message('Device "{}" updated successfully.'.format(self.object), self.request)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('core:device-list')


class DeviceFixMacView(PermissionRequiredMixin, UpdateView):
    permission_required = {
        'get': 'core.view_device',
        'post': 'core.change_device'
    }
    pk_url_kwarg = 'pk'
    form_class = DeviceFixMacForm
    model = Device

    def form_invalid(self, form):
        return JsonResponse({'message': 'Invalid parameters', 'errors': form.errors}, status=400)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.mac_manufacture = self.object.fetch_mac_manufacture()
        self.object.save()
        return JsonResponse(to_dict(self.object, fields=['id', 'name', 'address', 'mac']))


class DiscoverDeviceView(PermissionRequiredMixin, View):
    permission_required = 'core.add_device'
    template_name = "network_monitor/core/device/discover.html"

    def get_form(self):
        data = None
        if self.request.method == 'POST':
            data = self.request.POST
        return DiscoverDeviceForm(data=data)

    @staticmethod
    def _get_discovered_devices(scan):
        discovered_devices = []
        for ip, data in scan.items():
            mac = data.get('vendor', {}).get('mac')
            hostnames = [d.get('name') for d in data.get('hostnames', []) if d.get('name') ]
            status = 'new'
            manufacture = None
            if mac:
                device = Device.objects.filter(Q(address=ip)|Q(mac=mac)).first()
            else:
                device = Device.objects.filter(address=ip).first()
            if device:
                if mac and (device.mac != mac):

network_monitor/network_monitor/core/templates/network_monitor/core/user_alert_rule/add.html
{% extends "network_monitor/core/user_alert_rule/edit.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block breadcrumb_items %}
<li><a href="{% url 'core:user_alert_rule-list' %}">Alert Rules</a></li>
<li>New Alert Rule</li>
{% endblock %}

{% block content %}
<h3 class="page-title">Add New Alert Rule</h3>

<form name="rule-form" class="form-horizontal" enctype="multipart/form-data" method="post">
  {% block form-controls %}
    {{block.super}}
  {% endblock form-controls %}
  <hr>
  <div class="form-group">
    <label class="col-md-2 control-label"></label>
    <div class="col-md-9">
      <button type="submit" class="btn btn-primary" name="submit">Save</button>
      <a class="btn btn-default" href="{% url 'core:user_alert_rule-list' %}">Cancel</a>
    </div>
  </div>

</form>
{% endblock %}

network_monitor/network_monitor/core/templates/network_monitor/core/user_alert_rule/edit.html
{% extends "network_monitor/core/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block extra_css %}
  <link href="{{ STATIC_URL }}css/bootstrap-toggle.min.css" rel="stylesheet">
{% endblock %}


{% block breadcrumb_items %}
<li><a href="{% url 'core:user_alert_rule-list' %}">Alert Rules</a></li>
<li>Edit Alert Rule</li>
{% endblock %}

{% block content %}
<h3 class="page-title">Edit Alert Rule "{{object}}"</h3>

<form name="rule-form" class="form-horizontal" enctype="multipart/form-data" method="post">
  {% block form-controls %}
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' form_group_class='form-group row' horizontal_label_class='col-md-2' exclude='rules,custom_message' %}
  <div class="form-group row">
      <label class="col-md-1 control-label"></label>
      <button type="button" id="toggle-advanced-options" data-toggle="collapse" data-target="#alert-rule-advanced-options" class="btn btn-link">
          <span class="fa {% if form.instance.custom_message %}fa-minus{% else %}fa-plus{% endif %}"></span> Advanced options
      </button>
  </div>
  <div class="form-group row collapse {% if form.instance.custom_message %}in{% endif %}" id="alert-rule-advanced-options">
      <label class="col-md-2 control-label">{{ form.custom_message.label }}</label>
      <div class="col-md-9">
        <div id="" class="">
            {% bootstrap_field form.custom_message show_label=False %}
        </div>
      </div>
  </div>

  <div class="form-group row">
      <label class="col-md-2 control-label" for="rule_join_by">Where</label>
      <div class="col-md-9">
        <select name="join_by" id="rule_join_by">
          <option value='and' {% if form.instance.rules.join_by == 'and' %}selected{% endif %}>All</option>
          <option value='or' {% if form.instance.rules.join_by == 'or' %}selected{% endif %}>Any</option>
        </select> of the following rules:
      </div>
  </div>
  <div class="form-group row">
      <label class="col-md-2 control-label" for="">Rules</label>
      <input type="hidden" name="rules" id="id_rules">
      <div class="col-md-9">
        <div class="well">
          <table id="rules-table" class="table table-striped table-bordered">
            <thead>
              <tr>
                <th>Parameter</th><th>Comparator</th><th>Condition value</th><th class="rule-conds-table-actions-col">Action</th>
              </tr>
            </thead>
            <tbody>
            </tbody>
          </table>
        </div>
      </div>
  </div>
  {% endblock form-controls %}
  <hr>
  <div class="form-group">
    <label class="col-md-2 control-label"></label>
    <div class="col-md-9">
      <button type="submit" class="btn btn-primary" name="submit">Save</button>
      <a class="btn btn-default" href="{% url 'core:user_alert_rule-list' %}">Cancel</a>
      <span class="pull-right">
        <button type="button" class="btn btn-danger" name="delete"><span class="fa fa-trash"></span> Delete</button>
      </span>
    </div>
  </div>
</form>

{% url 'core:user_alert_rule-delete' object.id as delete_action %}
{% include "network_monitor/core/partials/action_modal.html" with prefix_id='action' message_class='text-danger' title='Delete Device' message='Are you sure to delete?' action=delete_action %}

{% endblock %}
{% block extra_js %}
{{form.media}}
<script src="{{ STATIC_URL }}js/bootstrap-toggle.min.js"></script>
<script src="{{ STATIC_URL }}js/utils.js"></script>

<script type="text/javascript">
$(document).ready(function () {
  $('.collapse').on('show.bs.collapse', function() {
    $(this).parent().find("#toggle-advanced-options .fa-plus").removeClass("fa-plus").addClass("fa-minus");
  }).on('hidden.bs.collapse', function() {
    $(this).parent().find(".fa-minus").removeClass("fa-minus").addClass("fa-plus")
  });
  bindModalAction('actionModal', 'button[name=delete]');
  ruleParamStruct = {
    severity: {
      choices: {{severity_choices|safe}},
      comparators: ['eq', 'neq', 'gt', 'gte', 'lt', 'lte']
    },
    device: {
      choices: {{device_choices|safe}},
      comparators: ['eq', 'neq']
    },
    feature: {
      choices: {{feature_choices|safe}},
      comparators: ['eq', 'neq']
    },
    threshold: {
      choices: {{threshold_choices|safe}},
      comparators: ['eq', 'neq']
    },
    summary: {
      comparators: ['eq', 'neq', 'contains', 'icontains', 'startswith', 'endswith']
    }
  };
  onChangeRuleP = function(combo) {
    var value = combo.value,
      ruleVSelect = $(combo).parents('tr').find('select[name=rule-v]'),
      ruleOSelect = $(combo).parents('tr').find('select[name=rule-o]');
    if (ruleParamStruct[value].choices == undefined) {
      $(combo).parents('tr').find('input[name=rule-v]').show().prop('required', true);
      ruleVSelect.hide().prop('required', false);;
    } else {
      $(combo).parents('tr').find('input[name=rule-v]').hide().prop('required', false);
      ruleVSelect.show().prop('required', true);
      ruleVSelect.find('option').remove();
      ruleParamStruct[value].choices.forEach(function(v) {
        ruleVSelect.append('<option value="'+v[0]+'">'+v[1]+'</option>');
      });
    }
    ruleOSelect.find('option').hide();
    ruleParamStruct[value].comparators.forEach(function(v) {
      ruleOSelect.find('option[value='+v+']').show();
    })
  };
  removeRule = function(elem) {
    if ($(elem).closest('tbody').find('tr').length == 1) {
      return;
    }
    $(elem).closest('tr').remove();
  };
  insertRule = function(afterElem) {
    tr = $('<tr><td><select name="rule-p" onchange="onChangeRuleP(this)"><option value="severity">severity</option><option value="feature">feature</option><option value="threshold">threshold</option><option value="device">device</option><option value="summary">summary</option></select></td><td><select name="rule-o"><option value="eq">Equal (=)</option><option value="neq">Not Equal (!=)</option><option value="gt">Greater than (>)</option><option value="gte">Greater than or equal to (>=)</option><option value="lt">Less than (<)</option><option value="lte">Less than or equal to (<=)</option><option value="contains">Contains(case sensitive)</option><option value="icontains">IContains(case insensitive)</option><option value="startswith">Starts with</option><option value="endswith">Ends with</option></select></td><td><input type="text" name="rule-v" style="display:none;"><select name="rule-v"></select></td><td><button type="button" name="rule-add" title="Insert After" class="btn btn-sm btn-success" onclick="insertRule(this)"><span class="fa fa-plus"></span></button> <button type="button" name="rule-delete" title="Delete" class="btn btn-sm btn-danger" onclick="removeRule(this)"><span class="fa fa-trash"></span></button></td></tr>')
    if (!afterElem) {
      $('#rules-table tbody').append(tr);
    } else {
      tr.insertAfter($(afterElem).closest('tr'));
    }
    onChangeRuleP(tr.find('select[name=rule-p]')[0])
    return tr;
  };

  initialRules = function () {
    var rules = {{form.instance.rules|safe}};
    if (!rules.conditions) {
      insertRule();
      return;
    }
    rules.conditions.forEach(function (c) {
      var tr = insertRule();
      tr.find('[name=rule-p]').val(c.p)[0].onchange();
      tr.find('[name=rule-v]:visible').val(c.v);
      tr.find('[name=rule-o]').val(c.o);
    });
  };
  $('form[name=rule-form]').submit(function() {
    var join_by = $('#rule_join_by').val(),
      conditions = [];
    $('#rules-table tbody tr').each(function(i, tr) {
      conditions.push({
        v: $(tr).find('[name=rule-v]:visible').val(),
        o: $(tr).find('[name=rule-o]:visible').val(),
        p: $(tr).find('[name=rule-p]:visible').val(),
      });
    });
    if (conditions.length == 0) {
      alert('No Rule Record!');
      return false;
    }
    var jdata = {
      join_by: join_by,
      conditions: conditions
    };
    $('#id_rules').val(JSON.stringify(jdata));
  });
  initialRules();
});
</script>
{% endblock %}

network_monitor/network_monitor/core/templates/network_monitor/core/user_alert_rule/list.html
{% extends "network_monitor/core/base.html" %}
{% load humanize %}
{% load pagination_tags %}
{% load util_tags %}

{% block extra_css %}
    <link href="{{ STATIC_URL }}css/chosen.min.css" rel="stylesheet">
{% endblock %}

{% block breadcrumb_items %}
<li>Alert Rules</li>
{% endblock %}

{% block content %}
    <a href="{% url 'core:user_alert_rule-add' %}" class="btn btn-success pull-right"><span class="fa fa-plus"></span> New Alert Rule</a><h3 class="page-title">Alert Rule List</h3>

    <table class="table table-hover table-advance">
        <tr>
            <th>Name</th>
            <th>Notify by</th>
            <th>Enabled?</th>
            <th class="alert-rule-list-table-actions-col">Actions</th>
        </tr>
        {% for rule in alert_rules %}
        <tr data-id="{{rule.id}}">
            <td><a href="{% url 'core:user_alert_rule-edit' rule.pk %}">{{ rule.name|title }}</a></td>
            <td>{{ rule.notify_media|join:', ' }}</td>
            <td>{{ rule.active|active_icon }}</td>
            <td>
                <a class="btn btn-sm btn-default" title="Edit Alert Rule" href="{% url 'core:user_alert_rule-edit' rule.pk %}"><span class="fa fa-pencil"></span></a>
                {% if rule.active %}
                <button name="disable-rule" class="btn btn-sm btn-warning" title="Disable Rule"><span class="fa fa-close"></span></button>
                {% else %}
                <button name="enable-rule" class="btn btn-sm btn-success" title="Enable Rule"><span class="fa fa-check"></span></button>
                {% endif %}
                <button class="btn btn-sm btn-danger" title="Delete Alert Rule" name="delete-rule"><span class="fa fa-trash"></span></button>
            </td>
        </tr>
        {% empty %}
        <tr><td class="text-center gray-color" colspan="8"> <em>[NO RECORD!]</em></td></tr>
        {% endfor %}
    </table>

{% include "network_monitor/core/partials/action_modal.html" with prefix_id='action' message_class='text-danger' %}
{% endblock %}

{% block extra_js %}
<script src="{{ STATIC_URL }}js/chosen.jquery.min.js"></script>
<script src="{{ STATIC_URL }}js/utils.js"></script>

<script type="text/javascript">
$(document).ready(function () {
    bindModalAction('actionModal', 'button[name=delete-rule]', 'Delete Alert Rule', 'Are you sure to delete?', '{% url 'core:user_alert_rule-delete' 0 %}');
    bindModalAction('actionModal', 'button[name=enable-rule]', 'Enable Alert Rule', 'Are you sure to Enable?', '{% url 'core:user_alert_rule-switch-active' 0 %}');
    bindModalAction('actionModal', 'button[name=disable-rule]', 'Disable Alert Rule', 'Are you sure to Disable?', '{% url 'core:user_alert_rule-switch-active' 0 %}');

});
</script>
{% endblock %}