network_monitor/network_monitor/core/urls.py
from django.conf.urls import url, include
from django.conf import settings

from network_monitor.helpers.utils import NotFoundView
from .views import IndexView, RegisterView, LoginView, LogoutView, \
    ProfileView, ChangePasswordView, DeviceListView, DeviceAddView, \
    DeviceEditView, DeviceDeleteView, DeviceFeaturesView, EventListView, \
    EventDeleteView, UserAlertRuleListView, UserAlertRuleAddView, \
    UserAlertRuleEditView, UserAlertRuleDeleteView, DeviceSwitchActiveView, UserAlertRuleSwitchActiveView, \
    DevicesStatusAjaxView, DevicePrintLabelView, DiscoverDeviceView, StopDiscoverDeviceView, DeviceFixMacView, \
    PingTestDeviceView, SettingGeneralView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^register/$', (RegisterView if settings.ENABLE_REGISTER_USER_VIEW else NotFoundView).as_view(),
        name="register"),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^profile/$', ProfileView.as_view(), name="profile"),
    url(r'^change-password/$', ChangePasswordView.as_view(), name="change-password"),
    url(r'^event/list/$', EventListView.as_view(), name="event-list"),
    url(r'^event/delete/(?P<pk>\d+)/$', EventDeleteView.as_view(), name="event-delete"),
    url(r'^device/list/$', DeviceListView.as_view(), name="device-list"),
    url(r'^device/add/$', DeviceAddView.as_view(), name="device-add"),
    url(r'^device/discover/$', DiscoverDeviceView.as_view(), name="device-discover"),
    url(r'^device/discover/stop/$', StopDiscoverDeviceView.as_view(), name="device-discover-stop"),
    url(r'^device/edit/(?P<pk>\d+)/$', DeviceEditView.as_view(), name="device-edit"),
    url(r'^device/fixmac/(?P<pk>\d+)/$', DeviceFixMacView.as_view(), name="device-fixmac"),
    url(r'^device/switch-active/(?P<pk>\d+)/$', DeviceSwitchActiveView.as_view(), name="device-switch-active"),
    url(r'^device/delete/(?P<pk>\d+)/$', DeviceDeleteView.as_view(), name="device-delete"),
    url(r'^device/print-label/(?P<pk>\d+)/$', DevicePrintLabelView.as_view(), name="device-print-label"),
    url(r'^device/features/(?P<pk>\d+)/$', DeviceFeaturesView.as_view(), name="device-features"),
    url(r'^device/status/(?P<pk>((\d+),?)+)/$', DevicesStatusAjaxView.as_view(), name="device-status"),
    url(r'^device/ping-test/(?P<pk>\d+)/$', PingTestDeviceView.as_view(), name="device-ping-test"),
    url(r'^user_alert_rule/list/$', UserAlertRuleListView.as_view(), name="user_alert_rule-list"),
    url(r'^user_alert_rule/add/$', UserAlertRuleAddView.as_view(), name="user_alert_rule-add"),
    url(r'^user_alert_rule/edit/(?P<pk>\d+)/$', UserAlertRuleEditView.as_view(), name="user_alert_rule-edit"),
    url(r'^user_alert_rule/switch-active/(?P<pk>\d+)/$', UserAlertRuleSwitchActiveView.as_view(), name="user_alert_rule-switch-active"),
    url(r'^user_alert_rule/delete/(?P<pk>\d+)/$', UserAlertRuleDeleteView.as_view(), name="user_alert_rule-delete"),
    url(r'^settings/general', SettingGeneralView.as_view(), name="settings-general"),
]

network_monitor/network_monitor/features/nmap/urls.py
from django.conf.urls import url

urlpatterns = [
]

network_monitor/network_monitor/features/ping/urls.py
from django.conf.urls import url

from .views import DeviceFeatureConfigView, DeviceFeatureChartsView


urlpatterns = [
    url(r'^config/$',
        DeviceFeatureConfigView.as_view(), name="device-feature-config"),
    url(r'^charts/$',
        DeviceFeatureChartsView.as_view(), name="device-feature-charts"),

]

network_monitor/network_monitor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from network_monitor.core.views import DeviceFeatureConfigView, DeviceFeatureChartsView, \
    DeviceFeatureThresholdListView, DeviceFeatureThresholdDeleteView, \
    DeviceFeatureThresholdSwitchView, DeviceFeatureThresholdAddView


urlpatterns = [
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
    url(r'', include('network_monitor.core.urls', namespace='core')),
]
for app in settings.INSTALLED_FEATURES:
    f = app.split('.')[-3]
    app_urls = '.'.join(app.split('.')[:-2]+['urls'])
    urlpatterns.append(url(r'^device/(?P<device_id>\d+)/{}/'.format(f), include(app_urls), kwargs={'feature': f}))

# default device_features routing
urlpatterns.extend([
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/config/$',
        DeviceFeatureConfigView.as_view(), name="device-feature-config"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/charts/$',
        DeviceFeatureChartsView.as_view(), name="device-feature-charts"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/list/$',
        DeviceFeatureThresholdListView.as_view(),
        name="device-feature-threshold-list"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/add/(?P<threshold_type>.+)/$',
        DeviceFeatureThresholdAddView.as_view(),
        name="device-feature-threshold-add"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/delete/(?P<threshold_id>\d+)/$',
        DeviceFeatureThresholdDeleteView.as_view(),
        name="device-feature-threshold-delete"),
    url(r'^device/(?P<device_id>\d+)/(?P<feature>.+)/threshold/switch/(?P<threshold_id>\d+)/$',
        DeviceFeatureThresholdSwitchView.as_view(),
        name="device-feature-threshold-switch"),
])

network_monitor/network_monitor/features/nmap/models.py
from django.db import models

# Create your models here.

network_monitor/network_monitor/features/ping/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

from network_monitor.core.models import Device


class PingTime(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE,
                               related_name='ping_time')
    min_time = models.FloatField('Minimum Time(ms)', null=True)
    max_time = models.FloatField('Maximum Time(ms)', null=True)
    avg_time = models.FloatField('Avgerage Time(ms)', null=True)
    mdev_time = models.FloatField('Median Deviation(ms)', null=True)
    packet_loss = models.FloatField('Packet Loss(%)', default=0.0,
                                    validators=[MinValueValidator(0.0),
                                                MaxValueValidator(100.0)])
    timestamp = models.DateTimeField('Timestamp', default=timezone.now)

    def __str__(self):
        return 'Ping(device={}, Loss={})'.format(self.device, self.packet_loss)

network_monitor/network_monitor/core/views.py
import json
import subprocess

from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import Http404
from django.views.generic.base import TemplateView
from django.views.generic import View
from django.views.generic.edit import UpdateView
from django.conf import settings
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.views import password_change
from django.views.generic.edit import CreateView
from django.views.generic.detail import SingleObjectMixin
from dynamic_preferences.forms import global_preference_form_builder
from dynamic_preferences.registries import global_preferences_registry

from network_monitor.celery import app
from network_monitor.helpers.shortcuts import get_redis_mem
from network_monitor.core.tasks import nmap_scan_network
from network_monitor.helpers.utils import send_form_errors, success_message, \
    PermissionRequiredMixin, get_current_page_size, find_mac_manufacture, to_dict, warning_message
from .forms import RegistrationForm, LoginForm, ProfileForm, DeviceForm, \
    DeviceFeatureForm, ThresholdForm, UserAlertRuleForm, DiscoverDeviceForm, DeviceFixMacForm
from .filters import DevicesFilter, EventsFilter
from .models import Device, DeviceFeature, Threshold, Event, UserAlertRule, \
    SEVERITY_CHOICES
try:
    from network_monitor.helpers.utils import py2_subprocess_run as subprocess_run
except ImportError:
    from subprocess import run as subprocess_run


class IndexView(PermissionRequiredMixin, View):
    permission_required = ()

    def get(self, request, *args, **kwargs):
        ctx = {}
        return render(request, "network_monitor/core/index.html", ctx)


class RegisterView(View):

    def get(self, request, *args, **kwargs):
        form = RegistrationForm()
        ctx = {"form": form}
        return render(request, "network_monitor/core/register.html", ctx)

    def post(self, request, *args, **kwargs):
        form = RegistrationForm(request.POST)
        password = request.POST.get('password')
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(password)
            user.save()
            success_message('User registered successfully', request)
            return redirect(self.get_success_url())
        else:
            send_form_errors(form, request)
        ctx = {"form": form}
        return render(request, "network_monitor/core/register.html", ctx)

    def get_success_url(self):
        return settings.LOGIN_URL


class LoginView(View):
    template_name = "network_monitor/core/login.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect(settings.LOGIN_REDIRECT_URL)
        form = LoginForm()
        ctx = {"form": form}
        return render(request, self.template_name, ctx)

    def post(self, request, *args, **kwargs):
        form = LoginForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            next = request.GET.get('next') or settings.LOGIN_REDIRECT_URL
            return redirect(next)
        else:
            send_form_errors(form, request)
        ctx = {"form": form}
        return render(request, self.template_name, ctx)


class LogoutView(View):

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return redirect(settings.LOGIN_URL)


class ProfileView(PermissionRequiredMixin, UpdateView):
    permission_required = ()
    form_class = ProfileForm
    template_name = 'network_monitor/core/profile.html'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        result = super(ProfileView, self).form_valid(form)
        success_message('Profile updated successfully.', self.request)
        return result

    def get_initial(self):
        profile = self.object.profile
        return {
            field: getattr(profile, field, None)
            for field in self.form_class.Meta._profile_fields
        }

    def get_success_url(self):
        return reverse('core:profile')


class ChangePasswordView(PermissionRequiredMixin, View):
    permission_required = ()

    def get(self, request, *args, **kwargs):
        self.get_success_url()
        return password_change(
            request, template_name='network_monitor/core/change_password.html',
            post_change_redirect=self.get_success_url(),)

    def post(self, request, *args, **kwargs):
        redirect_url = self.get_success_url()
        response = password_change(
            request, template_name='network_monitor/core/change_password.html',
            post_change_redirect=redirect_url)
        if response.status_code == 302 and response.url == redirect_url:
            success_message('Password changed successfully.', request)
        return response

    def get_success_url(self):
        return reverse('core:profile')


class DeviceListView(PermissionRequiredMixin, View):
    permission_required = 'core.view_device'

    def get(self, request, *args, **kwargs):
        qs = Device.objects.order_by('-active', 'id', )
        devices = DevicesFilter(self.request.GET, queryset=qs)
        ctx = {'devices': devices, 'page_size': get_current_page_size(request)}
        return render(request, "network_monitor/core/device/list.html", ctx)


class DeviceAddView(PermissionRequiredMixin, CreateView):
    permission_required = 'core.add_device'
    form_class = DeviceForm
    template_name = 'network_monitor/core/device/add.html'

    def get_form(self, form_class=None):
        form = super(DeviceAddView, self).get_form(form_class=form_class)
        if not self.request.user.has_perm("core.access_device_secret_data"):
            for sf in Device.secret_fields():
                form.fields.pop(sf, None)
        return form

    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse({'message': 'Invalid parameters', 'errors': form.errors}, status=400)
        return super(DeviceAddView, self).form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.mac:
            self.object.mac_manufacture = self.object.fetch_mac_manufacture()
        self.object.save()
        if self.request.is_ajax():
            return JsonResponse(to_dict(self.object, fields=['id', 'name', 'address', 'mac']))

        success_message('Device "{}" created successfully.'.format(self.object), self.request)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('core:device-list')


class DeviceEditView(PermissionRequiredMixin, UpdateView):
    permission_required = {
        'get': 'core.view_device',
        'post': 'core.change_device'
    }
    pk_url_kwarg = 'pk'
    form_class = DeviceForm
    model = Device
    template_name = 'network_monitor/core/device/edit.html'

    def get_form(self, form_class=None):
        form = super(DeviceEditView, self).get_form(form_class=form_class)
        if not self.request.user.has_perm("core.access_device_secret_data"):
            for sf in Device.secret_fields():
                form.fields.pop(sf, None)
        return form

    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse({'message': 'Invalid parameters', 'errors': form.errors}, status=400)
        return super(DeviceEditView, self).form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if 'mac' in form.changed_data or not self.object.mac_manufacture:
            self.object.mac_manufacture = self.object.fetch_mac_manufacture()
        self.object.save()
        if self.request.is_ajax():
            return JsonResponse(to_dict(self.object, fields=['id', 'name', 'address', 'mac']))

        success_message('Device "{}" updated successfully.'.format(self.object), self.request)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('core:device-list')


class DeviceFixMacView(PermissionRequiredMixin, UpdateView):
    permission_required = {
        'get': 'core.view_device',
        'post': 'core.change_device'
    }
    pk_url_kwarg = 'pk'
    form_class = DeviceFixMacForm
    model = Device

    def form_invalid(self, form):
        return JsonResponse({'message': 'Invalid parameters', 'errors': form.errors}, status=400)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.mac_manufacture = self.object.fetch_mac_manufacture()
        self.object.save()
        return JsonResponse(to_dict(self.object, fields=['id', 'name', 'address', 'mac']))


class DiscoverDeviceView(PermissionRequiredMixin, View):
    permission_required = 'core.add_device'
    template_name = "network_monitor/core/device/discover.html"

    def get_form(self):
        data = None
        if self.request.method == 'POST':
            data = self.request.POST
        return DiscoverDeviceForm(data=data)

    @staticmethod
    def _get_discovered_devices(scan):
        discovered_devices = []
        for ip, data in scan.items():
            mac = data.get('vendor', {}).get('mac')
            hostnames = [d.get('name') for d in data.get('hostnames', []) if d.get('name') ]
            status = 'new'
            manufacture = None
            if mac:
                device = Device.objects.filter(Q(address=ip)|Q(mac=mac)).first()
            else:
                device = Device.objects.filter(address=ip).first()
            if device:
                if mac and (device.mac != mac):

network_monitor/network_monitor/features/nmap/views.py
from django.shortcuts import render

# Create your views here.

network_monitor/network_monitor/core/templates/network_monitor/core/base.html
{% extends "network_monitor/base.html" %}
{% block title %}Network Monitoring Dashboard{% endblock %}
{% block main_css %}
    {{ block.super }}
    <link href="{{ STATIC_URL }}css/dashboard.css" rel="stylesheet">
{% endblock %}

{% block breadcrumb %}
<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumb">
            <li><a href="{% url 'core:index' %}">Home</a></li>
            {% block breadcrumb_items %}
            {% endblock %}
        </ul>
    </div>
</div>
{% endblock %}
{% block header_navbar %}
{% include "network_monitor/core/header.html" %}
{% endblock header_navbar %}

network_monitor/network_monitor/core/templates/network_monitor/core/change_password.html
{% extends "network_monitor/core/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block breadcrumb_items %}
<li><a href="{% url 'core:profile' %}">Profile</a></li>
<li>Change Password</li>
{% endblock %}

{% block content %}
<h3 class="page-title">Change Your Password</h3>

<form class="form-horizontal" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  {% bootstrap_form form layout='horizontal' form_group_class='form-group row' horizontal_label_class='col-md-2' %}
  <hr>
  <div class="form-group">
    <label class="col-md-2 control-label"></label>
    <div class="col-md-9">
      <button type="submit" class="btn btn-primary" name="submit">Save</button>
      <a class="btn btn-default" href="{% url 'core:profile' %}">Cancel</a>
    </div>
  </div>

</form>
{% endblock %}

network_monitor/network_monitor/core/templates/network_monitor/core/header.html
{% load util_tags %}
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'core:index' %}"><span class="fa fa-desktop"></span> Network Monitoring</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
        {% if user.is_authenticated %}
          <ul class="nav navbar-nav">
            <li class="{% active_if 'core:device-list' 'core:device-add' 'core:device-edit' 'core:device-discover' 'core:device-features' %}"><a href="{% url 'core:device-list' %}"><span class="fa fa-th-list"></span> Devices</a></li>
            <li class="{% active_if 'core:event-list' %}"><a href="{% url 'core:event-list' %}"><span class="fa fa-bullhorn"></span> Events </a></li>
            <li class="{% active_if 'core:user_alert_rule-list' 'core:user_alert_rule-add'  'core:user_alert_rule-edit' %}"><a href="{% url 'core:user_alert_rule-list' %}"><span class="fa fa-bell"></span> Alert Rules</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown {% active_if 'core:user_alert_rule-list' %}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="fa fa-gears"></span> Settings <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'core:settings-general' %}"><span class="fa fa-gear"></span> General Settings</a></li>
              </ul>
            </li>
            <li class="dropdown {% active_if 'core:profile' %}">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Welcome, <strong>{{user.username}}</strong> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'core:profile' %}"><span class="fa fa-user"></span> Profile</a></li>
                <li><a href="{% url 'core:logout' %}"><span class="fa fa-sign-out"></span> Logout</a></li>
              </ul>
            </li>
          </ul>
        {% else %}
          <ul class="nav navbar-nav navbar-right">
            <li class="{% active_if 'core:login' %}"><a href="{% url 'core:login' %}"><span class="fa fa-sign-in"></span> Login</a></li>
          </ul>
        {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>

network_monitor/network_monitor/core/templates/network_monitor/core/index.html
{% extends "network_monitor/core/base.html" %}

{% block breadcrumb_items %}

{% endblock %}

{% block content %}
<h3 class="page-title">Home</h3>
<h4 class="text-warning"> we should show a summary of system as a charts or reports!</h4>

{% endblock %}

network_monitor/network_monitor/core/templates/network_monitor/core/login.html
{% extends "network_monitor/core/base.html" %}
{% load util_tags %}

{% block extra_css %}
<style type="text/css">
  body {
    padding-top: 40px;
    padding-bottom: 40px;
    background-color: #eee;
  }
</style>
{% endblock %}
{% block breadcrumb %}
{% endblock %}

{% block content %}
<div class="container">
    <div class="onl_login">
        <h3 class="onl_authTitle" data-toggle="tooltip" data-placement="bottom" title="Recommended: Lumen Theme">Login or <a href="{% url 'core:register' %}">Sign up</a></h3>
        <div class="row onl_row-sm-offset-3 onl_socialButtons">
          <div class="col-xs-2 col-sm-2">
            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-block onl_btn-google-plus" data-toggle="tooltip" data-placement="top" title="Google Plus">
              <i class="fa fa-google-plus fa-2x"></i>
              <span class="hidden-xs"></span>
            </a>
          </div>
    </div><br>

    <div class="row onl_row-sm-offset-3 onl_loginOr">
      <div class="col-xs-12 col-sm-6">
        <hr class="onl_hrOr">
        <span class="onl_spanOr">or</span>
      </div>
    </div>

    <div class="row onl_row-sm-offset-3">
      <div class="col-xs-12 col-sm-6">
        <form id="form-login" method="POST" class="form-horizontal" action="">
          {% csrf_token %}
          {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="{{field.id_for_label}}" class="col-sm-2 control-label">{{field.label}}</label>
                <div class="col-sm-6">
                  {{ field }}
                  {{ field.errors }}
                  {{ field.help_text }}
                </div>
            </div>
          {% endfor %}
          <div class="form-group">
              <div class="col-sm-offset-2 col-sm-6">
                <button type="submit" class="btn btn-primary">Login</button>
              </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

network_monitor/network_monitor/core/templates/network_monitor/core/profile.html
{% extends "network_monitor/core/base.html" %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block breadcrumb_items %}
<li>Profile</li>
{% endblock %}

{% block content %}
<h3 class="page-title">Edit Your Profile</h3>

<form class="form-horizontal" enctype="multipart/form-data" method="post">
  {% csrf_token %}
  <div class="form-group row">
    <label class="col-md-2 control-label" for="id_username">Username</label>
    <div class="col-md-9">
      <input class="form-control" id="id_username" maxlength="30" name="username" type="text" value="{{object.username}}" readonly>
    </div>
  </div>

  {% bootstrap_form form layout='horizontal' form_group_class='form-group row' horizontal_label_class='col-md-2' %}
  <hr>
  <div class="form-group">
    <label class="col-md-2 control-label"></label>
    <div class="col-md-9">
      <button type="submit" class="btn btn-primary" name="submit">Save</button>
      <a class="btn btn-default" href="{% url 'core:index' %}">Cancel</a>
      <div class="pull-right">
        <a class="btn btn-warning" href="{% url 'core:change-password' %}"><span class="fa fa-key"></span> Change Password</a>
      </div>
    </div>
  </div>

</form>
{% endblock %}

network_monitor/network_monitor/core/templates/network_monitor/core/register.html
{% extends "network_monitor/core/base.html" %}
{% load bootstrap3 %}

{% block main-container %}
<div class="form col-sm-offset-2 col-sm-8">

    <center><h2><strong>Sign Up</strong></h2></center>

      <form id="form-register" method="POST" class="form-horizontal" action="">
      {% csrf_token %}

      {% bootstrap_form form %}

      <div class="form-group">
          <button type="submit" class="btn btn-primary"><span class="fa fa-check"></span> Register</button>
          <a class="btn btn-default" href="{% url 'core:login' %}"><span class="fa fa-close"></span> Cancel</a>
      </div>
    </form>
      <hr>
</div>


{% endblock main-container %}

 {% block javascript %}

 <script type="text/javascript">
    $( document ).ready(function() {

    $("input[type='text']").addClass('form-control')
    $("input[type='email']").addClass('form-control')
    $("input[type='password']").addClass('form-control')
});
        </script>
  {% endblock %}